### ISSUE TITLE
Trying to add member which is already subscribed creates empty entry

### ISSUE THREAD

**Issue by Kahmoon** [codefog/contao-events_subscriptions#25] opened 2019-06-06 11:12 UTC
Hi,

when you add members manually in backend and select a member which already has subscribed, an error is shown "Member already subscribed" and it does not continue (correct behaviour) but it also creates an empty subsciption which is blocking a slot (bug).

greetings
Frank

**Comment by Kahmoon** [comment] 2019-06-06 14:08
Screenshots https://ibb.co/rpztNR3

**Comment by Kahmoon** [comment] 2019-07-01 15:36
Hi,

need to push this bug (sorry. We create a lot of empty slots when teachers add members manually.

Frank

**Comment by qzminski** [comment] 2019-07-08 15:01
Should be fixed in c67076e. Can you try it before I release a new version?

**Comment by Kahmoon** [comment] 2019-07-08 15:12
Sure, if you tell me how to install the dev version (composer line).

**Comment by Kahmoon** [comment] 2019-07-09 15:17
Just updated the files manually.

Looks good. The person which is already registered is not listed in the dropdown anymore.

Frank

**Comment by Kahmoon** [comment] 2019-07-09 15:21
Update: I adds an empty entry when i choose "members" from registration type and go back to overview without saving a new member.

**Comment by qzminski** [comment] 2019-07-09 15:35
> Update: I adds an empty entry when i choose "members" from registration type and go back to subscribers overview without saving a new member.

I am unable to reproduce this one:

1. Create a new subscription record.
2. Choose "Member" in "Type" field.
3. (page reloads)
4. Click the "Go back" button in the upper right corner.

There is no empty record for me. Did I miss something?

**Comment by Kahmoon** [comment] 2019-07-09 15:37
Correct workflow....this happens at my installation. But maybe i got an error while building the php files according to yiur changelog in https://github.com/codefog/contao-events_subscriptions/commit/c67076e0bc692ed6238f030a44503e8c52c8ab5d

Is the a dev version which i could install via composer?

**Comment by Kahmoon** [comment] 2019-07-09 15:44
OK, it was a caching problem. I cleared production cache and now this behaviour i gone. :-)

**Comment by qzminski** [comment] 2019-07-09 15:46
Great, just released 2.3.7 so you can update the regular way now.

**Closed by qzminski** 2019-07-09 15:46 UTC
Labels: bug

**Comment by Kahmoon** [comment] 2019-07-09 18:39
Its still not available in updates :-)

**Comment by qzminski** [comment] 2019-07-10 07:11
Please try again, maybe the Packagist did not update its cache back then. Now it should be fine: https://packagist.org/packages/codefog/contao-events_subscriptions

**Comment by Kahmoon** [comment] 2019-07-10 09:12
Still not available in updates. Maybe due to the changes i made manually?
