### ISSUE TITLE
Deleting subsciptions from duplicated events via backend generates "mailbomb"

### ISSUE THREAD

**Issue by Kahmoon** [codefog/contao-events_subscriptions#12] opened 2019-01-20 10:14 UTC
Hi,

as mentionened in issue https://github.com/codefog/contao-events_subscriptions/issues/11 there pops out another problem.

When you remove subscriptions via backend a mail to the user is generated. But when copying old events which has already subscriptions, you have to delete them afterwards in the new event. So a mail to every old subscriber is generated which is pretty bad :-(

Can i disable mails from removing users via backend at all?

VG Frank

**Comment by qzminski** [comment] 2019-01-21 07:53
As far as I remember this feature was requested in the past and I see no reason to delete it. Whether you subscribe or unsubscribe a user in the backend he should get notified about that. I think your real problem was caused by the #11 as it indeed caused a lot of unnecessary e-mail to be sent out. It has been fixed in 2.1.2 though.

**Closed by qzminski** 2019-01-21 07:53 UTC

**Comment by Kahmoon** [comment] 2019-01-21 08:22
Hmm ok. Thanks for the quick fix in #11 

Frank
